### ISSUE TITLE
Move errors to a separate file 

### ISSUE THREAD

**Issue by Adwaith-Rajesh** [pysonDB/pysonDB#41]
Hacktoberfest - task

issue -
   Currently all the errors raised by pysondb are in the same file where JsonStorage class is. This is not considered to be a good practice. So moving the errors to a different file (errors.py) will make the code base look more concise and beautiful.

**Comment by Shylajhaa** [comment]
@Adwaith-Rajesh Is this issue available to work on?

**Comment by fredysomy** [comment]
Yes @Shylajhaa this issue is open to work on.

Join the discord for more updates.https://discord.gg/jyVFQtJ9yZ

**Comment by Shylajhaa** [comment]
> Yes @Shylajhaa this issue is open to work on.
> 
> Join the discord for more updates.https://discord.gg/jyVFQtJ9yZ

Can you assign it to me?

**Comment by fredysomy** [comment]
Sure , thanks

**Comment by jakbin** [comment]
Can I also create pull request for this ??

**Comment by jakbin** [comment]
> Can I also create pull request for this ??

please reply

**Comment by Adwaith-Rajesh** [comment]
Shylajhaa is working on it

**Comment by fredysomy** [comment]
#79

**Comment by Shylajhaa** [comment]
@fredysomy Guess this has been taken up. Sorry, couldn't find time to work on this at all :( . Would definitely love to work with `pysonDB` on any future issues.

**Comment by fredysomy** [comment]
No issues.😀
