### ISSUE TITLE
Units Tests

### ISSUE THREAD

**Issue by fredysomy** [pysonDB/pysonDB#45]
We need to develop some test cases as the existing ones are outdated.

**Comment by BodaleDenis** [comment]
Hi, I would like to work on this, if you can assign.

Thank you ! 😁😁

**Comment by fredysomy** [comment]
Hey @BodaleDenis Thanks, I will asign it to you.

**Comment by SwarajBaral** [comment]
hey @BodaleDenis can I also help in this ? I will be needing a bit of guidance in this though ?

**Comment by fredysomy** [comment]
Hey @SwarajBaral , we can help in any way we can from the discord group.

**Comment by SwarajBaral** [comment]
Hey @fredysomy which particular test areas would you like me to cover ? And can you please link the discord invite here ?

**Comment by Adwaith-Rajesh** [comment]
@SwarajBaral for now just test the core functionality, we can write the test for the CLI later

**Comment by Adwaith-Rajesh** [comment]
@SwarajBaral  here is the invite linkl
https://discord.gg/YNsUWy94k3

**Comment by jakbin** [comment]
@fredysomy can you assign me for this issue ?

**Comment by fredysomy** [comment]
@jakbin since i didnt get any replies from them i guess you can work on it.

**Comment by Adwaith-Rajesh** [comment]
we need to wait till all the issues are solved and all the branches are merged, so @jakbin pls wait

**Comment by fredysomy** [comment]
Thanks for the contribution @jakbin for the tests.
