### ISSUE TITLE
to store sensitive data like :password & public key or private key

### ISSUE THREAD

**Issue by TCP-88** [pysonDB/pysonDB#74]
**How would this feature be useful?**
to store sensitive data

**Describe the solution you'd like**
maybe encode and decode, a simple one

**Describe alternatives you've considered**

**Comment by Adwaith-Rajesh** [comment]
why can't you just hash it yourself? It would be much better than use implementing this. If you are doing the hash then you can pick your own algorithm, your own keys. That's better

**Comment by fredysomy** [comment]
Basic idea of pysonDB is to provide a way to interact with json.
