### ISSUE TITLE
Only one UniqueID will be find

### ISSUE THREAD

**Issue by DoM1niC** [pysonDB/pysonDB#87]
## Info
pyVersion: Python 3.10
OS: Windows 10
# **Describe the bug**
Only the latest added entry can be found else this error accrued
`pysondb.errors.db_errors.IdNotFoundError: Id '184766099262345250' does not exist in the JSON db`
**How to reproduce**

## GET Output
```
[
  {
    "id": 130978302791852290, 
    "name": "lol", 
    "state": true
  }, 
  {
    "id": 184766099262345253, 
    "name": "lol", 
    "state": true
  }, 
  {
    "id": 135312220569528861, 
    "name": "lol", 
    "state": true
  }
]

```
## Used Code e.g. Delete Data by ID
```
        id = data["id"]
        database=db.getDb("data.json")
        #id =database.getBy({"id":id})
        database.deleteById(id)
        return id + " deleted"
```
If I delete the last one ID in this Out here 135312220569528861 this works fine but another IDs couln't be found.
**Expected behavior**

Find the correct ID

**Comment by kollcorp-fredy** [comment]
Hey.

Can you please give more context in this issue.

**Comment by fredysomy** [comment]
Hey.

Can you give some more context. And it will be great if you can show how the .json file looks like.

**Comment by DoM1niC** [comment]
> Hey.
> 
> Can you give some more context. And it will be great if you can show how the .json file looks like.

```
{
   "data": [
      {
         "name": "dddww",
         "state": true,
         "id": 200545294469706682
      },
      {
         "name": "lol",
         "state": true,
         "id": 274100331642358635
      },
      {
         "name": "lol",
         "state": true,
         "id": 107191068313868653
      },
      {
         "name": "lol",
         "state": true,
         "id": 228355463568185490
      }
   ]
}
```

**Comment by fredysomy** [comment]
I suppose you are dynamically taking values from
`[
  {
    "id": 130978302791852290, 
    "name": "lol", 
    "state": true
  }, 
  {
    "id": 184766099262345253, 
    "name": "lol", 
    "state": true
  }, 
  {
    "id": 135312220569528861, 
    "name": "lol", 
    "state": true
  }
]
`

and deleting it Using the code 

`
        id = data["id"]
        database=db.getDb("data.json")
        #id =database.getBy({"id":id})
        database.deleteById(id)
        return id + " deleted"
`
Right

**Comment by DoM1niC** [comment]
> I suppose you are dynamically taking values from `[ { "id": 130978302791852290, "name": "lol", "state": true }, { "id": 184766099262345253, "name": "lol", "state": true }, { "id": 135312220569528861, "name": "lol", "state": true } ] `
> 
> and deleting it Using the code
> 
> `id = data["id"] database=db.getDb("data.json") #id =database.getBy({"id":id}) database.deleteById(id) return id + " deleted"` Right

yes I insert some to data.json by your insert feature this works fine after this I try to edit or remove someone by ID and this failed here, the get works too...

**Comment by DoM1niC** [comment]
```
def jsondb_get():
    database=db.getDb(databaseFile)
    return database.getAll()

def jsondb_delete(id):
    database=db.getDb(databaseFile)
    return database.deleteById(id)

def jsondb_update(id, data):
    database=db.getDb(databaseFile)
    return database.updateById(id,data)

@app.route("/api",methods=["POST","PUT","GET","DELETE","PATCH"])
def api():
    data = request.form
    methode = request.method

    match methode:
        case "GET":
            database=db.getDb("data.json")
            return jsonify(jsondb_get())

        case "POST":
            database=db.getDb(databaseFile)
            type = data["type"]
            match type:
                case "add":
                    name = data["name"]
                    database.add({"name":name,"state":True})
                    return name + " added"
                    
                case "update":
                    id = data["id"]
                    data = data["data"]
                    #database.update({"name":"Pyson-CLI"},{"name":"PysonCLI"})
                    data = {"name":data}
                    jsondb_update(id, data)
                    return data + " updated"
    
        case "DELETE":
            id = data["id"]
            jsondb_delete(id)
            return id + " deleted"

```
A bit more Code from my example Project :)

**Comment by fredysomy** [comment]
Hey .
Thanks for the info,

Will get back to you.

**Comment by fredysomy** [comment]
@Adwaith-Rajesh

**Comment by DoM1niC** [comment]
I see the new Changes but
- Fixed unicode being encoded as ASCII 
isn't help I execute pip3 install --force-reinstall --upgrade https://github.com/pysonDB/pysonDB/archive/refs/heads/master.zip
to pull the changes from master....

**Comment by DoM1niC** [comment]
Fixed by change some on DB init order 

```
TestDB = db.getDb("data.json")
usersDB = db.getDb("users.json")

def jsondb_getall(database):
    return database.getAll()

def jsondb_get(database, data):
    return database.getByQuery(data)

def jsondb_insert(database, data):
    return database.add(data)

def jsondb_delete(database, id):
    return database.deleteById(id)

def jsondb_update(database, id, data):
    return database.updateById(id,data)
```
