### ISSUE TITLE
Doc URLs in README not reachable

### ISSUE THREAD

**Issue by js-on** [pysonDB/pysonDB#89]
The weblinks to the pysonDB documentation like [this](https://fredysomy.me/pysonDB/docs/get) and [this](https://fredysomy.me/pysonDB/docs/search) are not working: `This site can't be reached.`
Would be nice if they could be updated soon.

**Comment by fredysomy** [comment]
The URL's were not updated when we changed repo from my personal account to this org
You can visit this link: https://pysondb.github.io/pysonDB/

and the other routes can be accecsed by https://pysondb.github.io/pysonDB/get and https://pysondb.github.io/pysonDB/add etc

I will try to update this ASAP.

**Comment by fredysomy** [comment]
Resolved in #91
